// Generated by https://quicktype.io
export interface LoginData {
    correo: string;
    password: string;
}

export interface RegisterData {
    nombre: string;
    apellido: string;
    correo: string;
    password: string;
    ciudad: string;
    direccion: string;
}

export interface EditarData {
    id: string;
    nombre?: string;
    apellido?: string;
    password?: string;
    ciudad?: string;
    direccion?: string;
}
export interface LoginResponse {
    ok: boolean;
    usuario: Usuario;
    token:   string;
}

export interface Usuario {
    rol:    string;
    estado: boolean;
    google: boolean;
    nombre: string;
    apellido?: string;
    correo: string;
    uid:    string;
    img?: string;
    ciudad?: string;
    direccion?: string;
}
